name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...

  release:
    needs: test
    if: github.event_name == 'push' && !github.event.repository.fork && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/release.yml
